---
- name: Collecting data of hosts
  hosts: all
  become: True

  tasks:

  - name: Gather host facts
    debug:
      var: ansible_facts

  - name: Gather uptime
    set_fact:
      uptime_secs: "{{ansible_facts.uptime_seconds}}"

  - name: display up
    debug:
      msg: "Time for uptime is {{uptime_secs}} "


  - name: Convert iento DDMMYY
    set_fact:
      uptime_formt: "{{'%Y-%m-%d' | strftime(uptime_secs) }}"


  - name: display
    debug:
      msg: "Time for uptime is {{uptime_formt}} "
