---
- hosts: all
  become: true
  tasks:
  - name: update apt cache
    apt: 
      update_cache: yes 
  - name: install apache2 package
    apt:
      name: apache2 
  - name: start apache server
    service:
      name: apache2
      state: started
      enabled: yes
 

